name: build

on:
    push:
        branches:
            - main
        paths:
            - .github/workflows/build.yml
            - Makefile
    workflow_dispatch:

permissions:
    contents: write

env:
    SQLITE_VERSION: "3.49.1"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                    - os: windows-latest
                    - os: macos-latest

        steps:
            - uses: actions/checkout@v4

            - name: Download SQLite sources
              shell: bash
              run: |
                  make prepare-dist
                  make download-amalgamation
                  make download-extensions

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  make compile-linux
                  zip --junk-paths dist/misc-linux-x86.zip dist/misc/*.so

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              shell: bash
              run: |
                  make compile-windows
                  cd dist/misc
                  7z a ../misc-win-x64.zip *.dll

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: |
                  make compile-macos
                  zip --junk-paths dist/misc-macos.zip dist/misc/*.dylib

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/*.zip
                  file_glob: true
                  overwrite: true
                  tag: ${{ env.SQLITE_VERSION }}
